import { Notice } from "obsidian";
import { EXPORT_LABELS, ExportFormat, runExport } from "./exports";
import { ViewContext } from "./viewContext";

export interface ExportState {
  format: ExportFormat;
  includePlanned: boolean;
}

/**
 * Configuration generated from the notes.
 *
 * Nothing is written to the network — the plugin never touches a server. This tab produces text to
 * copy, or a note to keep beside the rest of the vault, which is as far as a documentation tool
 * should go.
 */
export function renderExport(root: HTMLElement, ctx: ViewContext, state: ExportState): void {
  const bar = root.createDiv({ cls: "brewin-lan-filterbar" });

  const select = bar.createEl("select");
  (Object.keys(EXPORT_LABELS) as ExportFormat[]).forEach((format) => select.createEl("option", { value: format, text: EXPORT_LABELS[format] }));
  select.value = state.format;

  const plannedLabel = bar.createEl("label", { cls: "brewin-lan-check" });
  const planned = plannedLabel.createEl("input", { type: "checkbox" });
  planned.checked = state.includePlanned;
  plannedLabel.createSpan({ text: "include planned kit" });

  bar.createSpan({ cls: "brewin-lan-filter-count", text: `domain: ${ctx.settings.lanDomain}` });

  const body = root.createDiv({ cls: "brewin-lan-exportbody" });

  const draw = (): void => {
    body.empty();
    const result = runExport(state.format, ctx.net, { domain: ctx.settings.lanDomain, includePlanned: state.includePlanned });

    const actions = body.createDiv({ cls: "brewin-lan-exportactions" });
    actions.createSpan({ cls: "brewin-lan-filter-count", text: `${result.count} line${result.count === 1 ? "" : "s"}` });
    actions.createEl("button", { text: "Copy", cls: "mod-cta" }).addEventListener("click", () => {
      void navigator.clipboard.writeText(result.text).then(
        () => new Notice(`${EXPORT_LABELS[state.format]} copied — ${result.count} lines.`),
        () => new Notice("Couldn't reach the clipboard.")
      );
    });
    actions.createEl("button", { text: "Save as a note" }).addEventListener("click", () => void save(ctx, state, result.text));

    const pre = body.createEl("pre", { cls: "brewin-lan-export" });
    pre.createEl("code", { text: result.text });

    if (result.skipped.length) {
      const box = body.createDiv({ cls: "brewin-lan-skipped" });
      box.createDiv({
        cls: "brewin-lan-skipped-head",
        text: `${result.skipped.length} device${result.skipped.length === 1 ? "" : "s"} left out`,
      });
      for (const skip of result.skipped) {
        const row = box.createDiv({ cls: "brewin-lan-kv" });
        row.createSpan({ cls: "brewin-lan-k", text: skip.device });
        row.createSpan({ cls: "brewin-lan-muted", text: skip.reason });
      }
    }
  };

  select.addEventListener("change", () => {
    state.format = select.value as ExportFormat;
    draw();
  });
  planned.addEventListener("change", () => {
    state.includePlanned = planned.checked;
    draw();
  });
  draw();
}

/** Writes the export into a note beside the device notes, so it is versioned with everything else. */
async function save(ctx: ViewContext, state: ExportState, text: string): Promise<void> {
  const folder = ctx.settings.devicesFolder.split("/").slice(0, -1).join("/") || ctx.settings.devicesFolder;
  const name = EXPORT_LABELS[state.format].replace(/[^A-Za-z0-9 ]+/g, " ").replace(/\s+/g, " ").trim();
  const path = `${folder}/Export — ${name}.md`;
  const fence = state.format === "markdown" ? "" : state.format === "csv" ? "csv" : "ini";
  const generated = new Date().toISOString().slice(0, 16).replace("T", " ");
  const wrapped =
    state.format === "markdown"
      ? text
      : ["```" + fence, text.trimEnd(), "```"].join("\n");
  const content = [
    "---",
    `up: "[[${ctx.settings.hubNote}]]"`,
    "tags:",
    "  - Network/Export",
    `generated: ${generated}`,
    "---",
    "",
    `# ${name}`,
    "",
    "> Generated by Brewin LAN from the device notes. Edit the notes, not this file.",
    "",
    wrapped,
    "",
  ].join("\n");

  const existing = ctx.app.vault.getAbstractFileByPath(path);
  if (existing) {
    const file = ctx.store.fileFor(path);
    if (file) await ctx.app.vault.modify(file, content);
  } else {
    await ctx.app.vault.create(path, content);
  }
  new Notice(`Saved to ${path}`);
  ctx.open(path);
}
